
spring:
  profiles:
    active: dev #指定要激活的配置
  resources:
    static-locations: classpath:/static #指定静态资源的位置
  thymeleaf:
    cache: false #禁用缓存
---

spring:
  profiles: dev
server:
  port: 8080


---

spring:
  profiles: test
server:
  port: 80


---
spring:
  profiles: prod
server:
  port: 80
  servlet:
    context-path: /lms